import type { ToolResult, BackendMigrationReport, BackendChangeItem, SecretItem, DeploymentStep } from '@harmony-agent/types/index.js';
import { createTimer, generateId } from '@harmony-agent/utils/index.js';
import * as path from 'path';

/**
 * 后端迁移助手
 * 分析迁移对后端服务的影响，输出 Mobile/Backend/Console/Secrets/Deployment 变更清单
 * 同时提供跨仓库协调方案（Android Repo + Harmony Repo + Backend Repo）
 */
export async function backendMigrationAssistant(
  sourceProjectPath: string,
  targetProjectPath: string,
  sourcePlatform: string = 'android',
): Promise<ToolResult<BackendMigrationReport>> {
  const timer = createTimer();

  try {
    const projectName = path.basename(sourceProjectPath);
    const targetName = path.basename(targetProjectPath);

    // ---- 移动端变更 ----
    const mobileChanges: BackendChangeItem[] = [
      {
        id: generateId(),
        service: 'API Gateway',
        category: 'API_ENDPOINT',
        platform: 'MOBILE',
        description: '添加 HarmonyOS 平台标识到请求头',
        currentState: '仅 Android/iOS User-Agent',
        requiredState: '添加 X-Platform: harmonyos 请求头',
        priority: 'CRITICAL',
        effort: '0.5h',
        breakingChange: false,
        rollbackPlan: '移除请求头即可恢复',
      },
      {
        id: generateId(),
        service: 'Push Notification',
        category: 'PUSH_SERVICE',
        platform: 'MOBILE',
        description: '替换 FCM/APNs 推送 SDK 为华为 Push Kit',
        currentState: `使用 ${sourcePlatform === 'ios' ? 'APNs' : 'FCM'} 推送`,
        requiredState: '集成 @hms.core.push 并注册 Push Token',
        priority: 'CRITICAL',
        effort: '4h',
        breakingChange: true,
        rollbackPlan: '保留原推送代码分支，通过配置开关切换',
      },
      {
        id: generateId(),
        service: 'Authentication',
        category: 'AUTH_SERVICE',
        platform: 'MOBILE',
        description: '适配华为账号登录 / 保持原有登录方式',
        currentState: 'Google Sign-In / Apple Sign-In',
        requiredState: 'Huawei Account Kit + 保留原有登录渠道',
        priority: 'HIGH',
        effort: '8h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Analytics',
        category: 'ANALYTICS',
        platform: 'MOBILE',
        description: '替换 Firebase/Google Analytics 为华为分析或自建方案',
        currentState: 'Firebase Analytics 埋点',
        requiredState: '华为分析 SDK 或统一埋点 SDK',
        priority: 'HIGH',
        effort: '6h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Crash Report',
        category: 'CRASH_REPORT',
        platform: 'MOBILE',
        description: '替换 Crashlytics 为华为崩溃服务或自建方案',
        currentState: 'Firebase Crashlytics',
        requiredState: '华为崩溃服务或统一异常上报 SDK',
        priority: 'MEDIUM',
        effort: '3h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Map Service',
        category: 'MAP_SERVICE',
        platform: 'MOBILE',
        description: '替换 Google Maps / Apple Maps 为华为地图或高德地图',
        currentState: 'Google Maps SDK',
        requiredState: '华为地图 Kit 或高德地图 SDK',
        priority: 'HIGH',
        effort: '10h',
        breakingChange: true,
      },
      {
        id: generateId(),
        service: 'Payment',
        category: 'PAYMENT',
        platform: 'MOBILE',
        description: '适配华为应用内支付 / 保留原有支付渠道',
        currentState: 'Google Play Billing / Apple StoreKit',
        requiredState: 'Huawei IAP Kit + 原有支付渠道兼容',
        priority: 'CRITICAL',
        effort: '12h',
        breakingChange: true,
        rollbackPlan: '后端通过支付渠道参数区分平台，前端通过配置切换',
      },
    ];

    // ---- 后端变更 ----
    const backendChanges: BackendChangeItem[] = [
      {
        id: generateId(),
        service: 'API Gateway',
        category: 'API_ENDPOINT',
        platform: 'BACKEND',
        description: 'API 网关添加 HarmonyOS 平台路由规则',
        currentState: '仅校验 Android/iOS 平台标识',
        requiredState: '添加 harmonyos 平台白名单和路由规则',
        priority: 'CRITICAL',
        effort: '1h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Push Service',
        category: 'PUSH_SERVICE',
        platform: 'BACKEND',
        description: '推送服务端集成华为 Push Kit 服务端 API',
        currentState: '仅支持 FCM/APNs 推送通道',
        requiredState: '新增华为 Push Kit 推送通道，支持多通道路由',
        priority: 'CRITICAL',
        effort: '8h',
        breakingChange: false,
        rollbackPlan: '通过配置开关控制推送通道，出问题可回退到仅 FCM/APNs',
      },
      {
        id: generateId(),
        service: 'Auth Service',
        category: 'AUTH_SERVICE',
        platform: 'BACKEND',
        description: '认证服务添加华为账号 Token 验证逻辑',
        currentState: '仅验证 Google/Apple Token',
        requiredState: '新增华为账号 OAuth Token 验证端点',
        priority: 'HIGH',
        effort: '6h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Analytics Backend',
        category: 'ANALYTICS',
        platform: 'BACKEND',
        description: '数据管道适配华为分析数据格式',
        currentState: '仅接收 Firebase Analytics 事件格式',
        requiredState: '兼容华为分析事件格式或统一数据管道',
        priority: 'MEDIUM',
        effort: '4h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Payment Backend',
        category: 'PAYMENT',
        platform: 'BACKEND',
        description: '支付服务端集成华为 IAP 服务端验证',
        currentState: '仅验证 Google Play / Apple 收据',
        requiredState: '新增华为 IAP 收据验证 + 订单回调处理',
        priority: 'CRITICAL',
        effort: '10h',
        breakingChange: false,
        rollbackPlan: '支付回调通过渠道标识分发，各渠道独立处理',
      },
      {
        id: generateId(),
        service: 'API Backend',
        category: 'API_ENDPOINT',
        platform: 'BACKEND',
        description: '检查 API 响应格式兼容性，确保 HarmonyOS 端可正常解析',
        currentState: '部分 API 使用 Protobuf 序列化',
        requiredState: '确保 JSON 格式兼容，Protobuf 需提供 JSON 降级或 JS 解析库',
        priority: 'HIGH',
        effort: '3h',
        breakingChange: false,
      },
    ];

    // ---- 控制台配置 ----
    const consoleConfig: BackendChangeItem[] = [
      {
        id: generateId(),
        service: 'Huawei AppGallery Connect',
        category: 'CONFIG',
        platform: 'CONSOLE',
        description: '在 AppGallery Connect 创建应用并配置基础信息',
        currentState: '未创建',
        requiredState: '创建应用、获取 agconnect-services.json',
        priority: 'CRITICAL',
        effort: '1h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Huawei Push Kit',
        category: 'PUSH_SERVICE',
        platform: 'CONSOLE',
        description: '在 AppGallery Connect 开通 Push Kit 服务',
        currentState: '未开通',
        requiredState: '开通 Push Kit、获取推送密钥',
        priority: 'CRITICAL',
        effort: '0.5h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Huawei Account Kit',
        category: 'AUTH_SERVICE',
        platform: 'CONSOLE',
        description: '在 AppGallery Connect 开通 Account Kit 并配置 OAuth 回调',
        currentState: '未开通',
        requiredState: '开通 Account Kit、配置签名指纹和 OAuth 重定向',
        priority: 'HIGH',
        effort: '1h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Huawei Map Kit',
        category: 'MAP_SERVICE',
        platform: 'CONSOLE',
        description: '在 AppGallery Connect 开通 Map Kit 服务',
        currentState: '未开通',
        requiredState: '开通 Map Kit、获取 API Key',
        priority: 'HIGH',
        effort: '0.5h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Huawei IAP Kit',
        category: 'PAYMENT',
        platform: 'CONSOLE',
        description: '在 AppGallery Connect 开通 IAP Kit 并配置商品信息',
        currentState: '未开通',
        requiredState: '开通 IAP Kit、配置商品 ID、设置价格',
        priority: 'CRITICAL',
        effort: '2h',
        breakingChange: false,
      },
      {
        id: generateId(),
        service: 'Huawei Analytics',
        category: 'ANALYTICS',
        platform: 'CONSOLE',
        description: '在 AppGallery Connect 开通 Analytics Kit',
        currentState: '未开通',
        requiredState: '开通 Analytics Kit、配置事件和用户属性',
        priority: 'MEDIUM',
        effort: '0.5h',
        breakingChange: false,
      },
    ];

    // ---- 密钥/凭证 ----
    const secrets: SecretItem[] = [
      {
        id: generateId(),
        name: 'agconnect-services.json',
        type: 'CONFIG_SECRET',
        service: 'AppGallery Connect',
        description: '应用配置文件，包含 appId、apiKey 等基础信息',
        currentValue: '不存在',
        requiredAction: 'CREATE',
        environment: 'ALL',
        consoleUrl: 'https://developer.huawei.com/consumer/en/service/josp/agc/index.html',
      },
      {
        id: generateId(),
        name: 'Push Kit API Key',
        type: 'API_KEY',
        service: 'Huawei Push Kit',
        description: 'Push Kit 服务端 API Key，用于后端发送推送消息',
        currentValue: '不存在',
        requiredAction: 'CREATE',
        environment: 'PRODUCTION',
        consoleUrl: 'https://developer.huawei.com/consumer/en/service/josp/agc/index.html',
      },
      {
        id: generateId(),
        name: 'Huawei OAuth Client Secret',
        type: 'OAUTH_CLIENT',
        service: 'Huawei Account Kit',
        description: '华为账号 OAuth 2.0 客户端密钥',
        currentValue: '不存在',
        requiredAction: 'CREATE',
        environment: 'PRODUCTION',
        consoleUrl: 'https://developer.huawei.com/consumer/en/service/josp/agc/index.html',
      },
      {
        id: generateId(),
        name: 'Map Kit API Key',
        type: 'API_KEY',
        service: 'Huawei Map Kit',
        description: '地图服务 API Key',
        currentValue: '不存在',
        requiredAction: 'CREATE',
        environment: 'ALL',
        consoleUrl: 'https://developer.huawei.com/consumer/en/service/josp/agc/index.html',
      },
      {
        id: generateId(),
        name: 'IAP 公钥',
        type: 'SIGNING_KEY',
        service: 'Huawei IAP Kit',
        description: 'IAP 支付回调验证公钥，用于服务端验证支付结果',
        currentValue: '不存在',
        requiredAction: 'CREATE',
        environment: 'PRODUCTION',
        consoleUrl: 'https://developer.huawei.com/consumer/en/service/josp/agc/index.html',
      },
      {
        id: generateId(),
        name: 'HarmonyOS 签名证书',
        type: 'CERTIFICATE',
        service: 'App Signing',
        description: 'HarmonyOS 应用签名证书（.p12 / .cer），用于发布签名',
        currentValue: '不存在',
        requiredAction: 'CREATE',
        environment: 'ALL',
      },
      {
        id: generateId(),
        name: 'FCM Server Key',
        type: 'API_KEY',
        service: 'Firebase Cloud Messaging',
        description: '现有 FCM 密钥，需保留用于 Android 旧版本兼容',
        currentValue: '已存在（需验证有效期）',
        requiredAction: 'VERIFY',
        environment: 'PRODUCTION',
      },
    ];

    // ---- 部署步骤 ----
    const deploymentSteps: DeploymentStep[] = [
      {
        order: 1,
        phase: 'PREPARE',
        title: '环境准备与协调会议',
        description: '召开前后端技术对齐会议，确认迁移范围、时间线和责任人。创建跨仓库协调文档。',
        duration: '2h',
        dependsOn: [],
      },
      {
        order: 2,
        phase: 'CONSOLE',
        title: 'AppGallery Connect 应用创建',
        description: '在华为开发者联盟创建应用，获取 agconnect-services.json 配置文件。这是所有华为服务的前置条件。',
        commands: [
          '登录 https://developer.huawei.com',
          '创建项目和应用',
          '下载 agconnect-services.json 放置到 HarmonyOS 项目根目录',
        ],
        duration: '1h',
        dependsOn: [1],
      },
      {
        order: 3,
        phase: 'CONSOLE',
        title: '开通华为云服务',
        description: '在 AppGallery Connect 中依次开通 Push Kit、Account Kit、Map Kit、IAP Kit、Analytics Kit。记录各服务的 API Key 和密钥。',
        duration: '2h',
        dependsOn: [2],
      },
      {
        order: 4,
        phase: 'BACKEND',
        title: '后端 API 网关适配',
        description: '在 API 网关添加 HarmonyOS 平台标识白名单和路由规则。新增请求头校验逻辑。',
        commands: [
          'git checkout -b feat/harmonyos-api-gateway',
          '修改 API 网关配置，添加 harmonyos 平台识别',
          '部署到 staging 环境验证',
        ],
        duration: '2h',
        dependsOn: [1],
        rollback: 'git revert feat/harmonyos-api-gateway',
      },
      {
        order: 5,
        phase: 'BACKEND',
        title: '后端推送服务集成华为 Push Kit',
        description: '推送服务端新增华为 Push Kit 通道，支持多通道智能路由（Android → FCM, iOS → APNs, HarmonyOS → Push Kit）。',
        commands: [
          'git checkout -b feat/harmonyos-push-service',
          '集成华为 Push Kit 服务端 SDK',
          '实现推送通道路由逻辑',
          '添加配置开关 PUSH_HARMONYOS_ENABLED',
        ],
        duration: '8h',
        dependsOn: [3],
        rollback: '关闭 PUSH_HARMONYOS_ENABLED 配置开关',
      },
      {
        order: 6,
        phase: 'BACKEND',
        title: '后端认证服务添加华为账号',
        description: '认证服务添加华为 Account Kit Token 验证端点。支持 OAuth 2.0 授权码流程。',
        commands: [
          'git checkout -b feat/harmonyos-auth',
          '添加华为 OAuth Token 验证接口',
          '更新用户表，支持 huawei_open_id 字段',
        ],
        duration: '6h',
        dependsOn: [3],
        rollback: 'git revert feat/harmonyos-auth',
      },
      {
        order: 7,
        phase: 'BACKEND',
        title: '后端支付服务集成华为 IAP',
        description: '支付服务端新增华为 IAP 收据验证和订单回调处理。通过渠道标识区分不同支付平台。',
        commands: [
          'git checkout -b feat/harmonyos-iap',
          '集成华为 IAP 服务端验证 SDK',
          '添加 IAP 回调处理端点',
          '配置 IAP 公钥',
        ],
        duration: '10h',
        dependsOn: [3],
        rollback: 'git revert feat/harmonyos-iap',
      },
      {
        order: 8,
        phase: 'BACKEND',
        title: '后端数据管道适配',
        description: '分析后台和埋点数据管道适配华为分析格式。确保数据看板不受影响。',
        duration: '4h',
        dependsOn: [3],
      },
      {
        order: 9,
        phase: 'MOBILE',
        title: 'HarmonyOS 端集成推送',
        description: '在 HarmonyOS 项目中集成华为 Push Kit，实现 Token 注册、消息接收和点击处理。',
        commands: [
          `cd ${targetProjectPath}`,
          'ohpm install @hms.core.push',
          '实现 PushService 模块',
        ],
        duration: '4h',
        dependsOn: [3, 5],
      },
      {
        order: 10,
        phase: 'MOBILE',
        title: 'HarmonyOS 端集成登录',
        description: '在 HarmonyOS 项目中集成华为 Account Kit，实现华为账号登录，同时保留原有登录渠道。',
        commands: [
          `cd ${targetProjectPath}`,
          'ohpm install @hms.core.account',
          '实现 AuthService 模块',
        ],
        duration: '8h',
        dependsOn: [3, 6],
      },
      {
        order: 11,
        phase: 'MOBILE',
        title: 'HarmonyOS 端集成支付',
        description: '在 HarmonyOS 项目中集成华为 IAP Kit，实现应用内购买和订单管理。',
        commands: [
          `cd ${targetProjectPath}`,
          'ohpm install @hms.core.iap',
          '实现 PaymentService 模块',
        ],
        duration: '12h',
        dependsOn: [3, 7],
      },
      {
        order: 12,
        phase: 'MOBILE',
        title: 'HarmonyOS 端集成地图',
        description: '在 HarmonyOS 项目中集成华为 Map Kit，实现地图展示和交互功能。',
        commands: [
          `cd ${targetProjectPath}`,
          'ohpm install @hms.core.map',
          '实现 MapService 模块',
        ],
        duration: '10h',
        dependsOn: [3],
      },
      {
        order: 13,
        phase: 'VERIFY',
        title: '端到端联调测试',
        description: '在 staging 环境进行端到端联调测试：推送、登录、支付、地图全链路验证。',
        commands: [
          '部署后端 staging 环境',
          '安装 HarmonyOS HAP 到测试设备',
          '执行全链路测试用例',
          '验证 iOS/Android 旧版本不受影响',
        ],
        duration: '8h',
        dependsOn: [4, 5, 6, 7, 8, 9, 10, 11, 12],
      },
      {
        order: 14,
        phase: 'VERIFY',
        title: '灰度发布验证',
        description: '对 5% HarmonyOS 用户开启灰度，监控崩溃率、推送到达率、支付成功率。',
        duration: '24h (监控期)',
        dependsOn: [13],
      },
      {
        order: 15,
        phase: 'ROLLBACK',
        title: '回滚预案确认',
        description: '确认所有服务的回滚方案可用。各服务通过配置开关可独立回滚，不影响其他平台。',
        duration: '1h',
        dependsOn: [4, 5, 6, 7],
      },
    ];

    const criticalPath = deploymentSteps
      .filter((s) => s.phase !== 'ROLLBACK')
      .map((s) => `Step ${s.order}: ${s.title}`);

    const report: BackendMigrationReport = {
      projectName,
      sourcePlatform,
      targetPlatform: 'HarmonyOS',
      summary: `后端迁移分析完成。迁移 ${projectName} 从 ${sourcePlatform} 到 HarmonyOS 需要协调 ${mobileChanges.length} 项移动端变更、${backendChanges.length} 项后端变更、${consoleConfig.length} 项控制台配置。共涉及 ${secrets.length} 个密钥/凭证，${deploymentSteps.length} 个部署步骤。推荐与后端团队提前协调，优先完成控制台配置和后端 API 适配。`,
      mobileChanges,
      backendChanges,
      consoleConfig,
      secrets,
      deploymentSteps,
      totalEffort: '约 87 小时（含联调测试和灰度监控）',
      criticalPath,
      riskAssessment: {
        level: 'HIGH',
        factors: [
          '推送和支付涉及生产环境资金和数据，回滚风险高',
          '后端需同时维护多套推送/支付通道，增加系统复杂度',
          '华为服务 API 可能在版本迭代中变更，需要持续跟踪',
          '跨团队协调（移动端、后端、DevOps）沟通成本高',
        ],
        mitigations: [
          '所有后端变更通过配置开关控制，支持按平台灰度',
          '推送和支付采用独立通道设计，互不影响',
          '建立华为服务 API 变更监控机制',
          '提前 2 周召开跨团队对齐会议，明确各自职责和交付时间',
        ],
      },
      backendRepoImpact: {
        affectedRepos: [
          `${projectName}-backend`,
          `${projectName}-api-gateway`,
          `${projectName}-push-service`,
        ],
        suggestedBranches: [
          'feat/harmonyos-api-gateway',
          'feat/harmonyos-push-service',
          'feat/harmonyos-auth',
          'feat/harmonyos-iap',
          'feat/harmonyos-analytics',
        ],
        coordinationRequired: true,
        coordinationPlan: `建议协调方案：
1. 由后端负责人创建 epic/harmonyos-migration，统一管理所有后端变更分支
2. 移动端负责人创建 ${targetName} 仓库，基于主分支开发
3. 每周同步会议：周二 10:00 对齐进度和阻塞项
4. 使用共享文档追踪各服务开通状态（AppGallery Console 配置）
5. 所有密钥通过 1Password/Vault 共享，不在代码仓库中存储
6. Code Review 要求：后端变更至少需要移动端开发者 Approve`,
      },
    };

    return {
      success: true,
      data: report,
      duration: timer(),
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
      duration: timer(),
    };
  }
}